# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 bet3rd

"""Persistence ports for account-manager data."""

from __future__ import annotations

from typing import Any, Protocol

from warestore.domain.accounts.models import AccountRecord


class TokenStore(Protocol):
    def load_all(self) -> dict[str, dict[str, Any]]: ...
    def save_all(self, tokens: dict[str, dict[str, Any]]) -> None: ...
    def store(self, steam_id: str, username: str, token: str) -> None: ...
    def remove(self, steam_id: str) -> bool: ...


class MetadataStore(Protocol):
    def get(self, steam_id: str) -> AccountRecord: ...
    def set_last_played(self, steam_id: str, played: bool = True) -> None: ...
    def set_cooldown(self, steam_id: str, duration_seconds: int) -> None: ...
    def clear_cooldown(self, steam_id: str) -> None: ...
    def delete(self, steam_id: str) -> None: ...


class SettingsStore(Protocol):
    def load(self) -> dict[str, Any]: ...
    def save(self, settings: dict[str, Any]) -> None: ...
